// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"time"

	"github.com/google/uuid"
)

type DeadJob struct {
	ID          uuid.UUID
	QueueName   string
	QueuedAt    time.Time
	ScheduledAt time.Time
	Data        []byte
	Attempt     int32
}

type QueuedJob struct {
	ID          uuid.UUID
	QueueName   string
	QueuedAt    time.Time
	ScheduledAt time.Time
	Data        []byte
	Attempt     int32
}
