// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeadLetter(ctx context.Context, arg DeadLetterParams) error
	DeadLetterCount(ctx context.Context) (int64, error)
	Dequeue(ctx context.Context, queueName string) (QueuedJob, error)
	Enqueue(ctx context.Context, arg EnqueueParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
