linters:
  enable:
    - misspell
    - bodyclose
    - deadcode
    - gofmt
    - goimports
    - gosimple
    - dogsled
    - durationcheck
    - goconst
    - godot
    - gosec
    - importas
    - paralleltest
    - whitespace
    - staticcheck
    - revive
