issues:
  exclude-use-default: false

linters:
  enable:
    - misspell
    - bodyclose
    - deadcode
    - gofmt
    - goimports
    - gosimple
    - dogsled
    - durationcheck
    - goconst
    - godot
    - gosec
    - importas
    - paralleltest
    - whitespace
    - staticcheck
    - revive
    - errcheck

linters-settings:
    gosec:
      excludes:
        - G104 # already checked by errcheck
        - G307 # already checked by errcheck
        - G304
