// Code generated by sqlc. DO NOT EDIT.
// source: health.sql

package store

import (
	"context"
)

const health = `-- name: Health :exec
SELECT 1
`

func (q *Queries) Health(ctx context.Context) error {
	_, err := q.db.Exec(ctx, health)
	return err
}
