// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type BuildRequest struct {
	ID         uuid.UUID
	Targets    []string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	CommitSha  string
	TreeSha    string
	Owner      string
	Repository string
}

type BuildToken struct {
	ID                 uuid.UUID
	BuildRequestID     uuid.UUID
	BuildRequestTarget string
	CreatedAt          time.Time
	ExpiredAt          sql.NullTime
	Token              string
}

type ReceiveToken struct {
	ID                 uuid.UUID
	BuildRequestID     uuid.UUID
	BuildRequestTarget string
	CreatedAt          time.Time
	ClaimedAt          sql.NullTime
	Token              string
}
