// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClaimReceiveToken(ctx context.Context, arg ClaimReceiveTokenParams) error
	CreateBuildRequest(ctx context.Context, arg CreateBuildRequestParams) (uuid.UUID, error)
	CreateBuildToken(ctx context.Context, arg CreateBuildTokenParams) (uuid.UUID, error)
	CreateReceiveToken(ctx context.Context, arg CreateReceiveTokenParams) (uuid.UUID, error)
	ExpireBuildToken(ctx context.Context, arg ExpireBuildTokenParams) error
	GetBuildRequest(ctx context.Context, id uuid.UUID) (BuildRequest, error)
	GetBuildRequestFromBuildToken(ctx context.Context, token string) (GetBuildRequestFromBuildTokenRow, error)
	GetBuildRequestFromReceiveToken(ctx context.Context, token string) (GetBuildRequestFromReceiveTokenRow, error)
}

var _ Querier = (*Queries)(nil)
