#!/bin/bash

if [[ -z ${SLUGCMPLR_ACC_HEROKU_PASS} ]] || [[ -z ${SLUGCMPLR_ACC_HEROKU_EMAIL} ]]; then

  echo "SLUGCMPLR_ACC_HEROKU_PASS and SLUGCMPLR_ACC_HEROKU_EMAIL must be set in the environment to run acceptance tests."
  exit 1
fi

echo "These tests will create resources in your Heroku account (${SLUGCMPLR_ACC_HEROKU_EMAIL})."

read -n 1 -s -r -p "Are you sure? (Press any key to continue)"; echo

echo "Running..."

export SLUGCMPLR_ACC="true"

go get -v -d
go test -v -race -parallel=4 ./...
