// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) error
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	ExpireToken(ctx context.Context, token string) error
	FetchWithToken(ctx context.Context, token string) (Compilation, error)
}

var _ Querier = (*Queries)(nil)
