name: acceptance

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 * * 3' # run at 09:30 UTC every wednesday
  push:
    branches: [ main ]
  pull_request:
    types: [labeled]
    branches: [ main ]

jobs:
  test:
    if: ${{ github.event_name == 'push' || github.event.label.name == 'run-acceptance-tests' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    name: Acceptance
    runs-on: ubuntu-latest
    env:
      SLUGCMPLR_ACC: "true"
      SLUGCMPLR_ACC_HEROKU_PASS: ${{ secrets.SLUGCMPLR_HEROKU_API_KEY }}
      SLUGCMPLR_ACC_HEROKU_EMAIL: ${{ secrets.SLUGCMPLR_HEROKU_EMAIL }}
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: .
        tags: ghcr.io/cga1123/slugcmplr:testing
        load: true
        build-args: STACK=20
    - run: go get -v -d ./...
    - run: go test -v -race -parallel=4 ./...
