name: acceptance

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 * * 3' # run at 09:30 UTC every wednesday
  push:
    branches: [ main ]
  pull_request:
    types: [labeled]
    branches: [ main ]

jobs:
  test:
    if: ${{ github.event_name == 'push' || github.event.label.name == 'run-acceptance-tests' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    name: Acceptance
    runs-on: ubuntu-latest
    env:
      SLUGCMPLR_ACC: "true"
      SLUGCMPLR_ACC_HEROKU_PASS: ${{ secrets.SLUGCMPLR_HEROKU_API_KEY }}
      SLUGCMPLR_ACC_HEROKU_EMAIL: ${{ secrets.SLUGCMPLR_HEROKU_EMAIL }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.17.x
    - run: go test -v -race -parallel=4 ./...
