name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - run: go get -u honnef.co/go/tools/cmd/staticcheck
    - run: go get -v -d ./...
    - run: go test -race -timeout=10s -coverprofile=coverage.out -parallel=4 ./...
    - run: go tool cover -html=coverage.out -o coverage.html
    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage.html
    - run: staticcheck ./...
    - run: go fmt ./...
