name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  containers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack: [ '18', '20' ]

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: CGA1123
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          tags:
            - ghcr.io/cga1123/slugcmplr:heroku-${{ matrix.stack }}
            - ghcr.io/cga1123/slugcmplr:heroku-${{ matrix.stack }}-${{ github.sha }}
          push: true
          build-args: STACK=${{ matrix.stack }}

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
