name: Release
on:
  push:
    tags:
      - '*'

jobs:
  containers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack: [ '18', '20' ]

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build \
            --build-arg STACK=${{ matrix.stack }}
            --tag ghcr.io/cga1123/slugcmplr:heroku-${{ matrix.stack }} \
            --tag ghcr.io/cga1123/slugcmplr:heroku-${{ matrix.stack }}-${{ github.sha }} \
            .
      - run: docker push --all-tags ghcr.io/cga1123/slugcmplr:heroku-${{ matrix.stack }}

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
